# Generated by Django 5.0.1 on 2024-01-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('foto', models.FileField(upload_to='produtos')),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Produtos',
        ),
    ]
